<?php
namespace dictionary;

/**
 * Description of en
 *
 * @author Solal Fitoussi <solal.fitoussi@gmail.com>
 */
class fr extends \CommonDictionary{

	
	protected function getWords() {
		return array(
			'a' => array('a','abandonner','abattre','aborder','abri','absence','absolu','absolument','accent','accepter','accompagner','accomplir','accord','accorder','accrocher','accueillir','accuser','acheter','achever','acte','action','admettre','adresser','affaire','affirmer','afin de','age','age','agent','agir','agiter','ah','aide','aider','aile','ailleurs','aimer','ainsi','air','ajouter','aller','allumer','alors','ame','amener','ami','amour','amuser','an','ancien','anglais','anglais','angoisse','animal','animer','annee','annoncer','apercevoir','apparaitre','apparence','appartement','appartenir','appel','appeler','apporter','apprendre','approcher','approuver','appuyer','apres','apres','arbre','argent','arme','armee','armer','arracher','arreter','arriere','arrivee','arriver','art','article','as','aspect','asseoir','assez','assister','assurer','attacher','attaquer','atteindre','attendre','attente','attention','attirer','attitude','au','aucun','aucun','aujourd\'hui','auparavant','aupres','auquel','aussi','aussitot','autant','auteur','autorite','autour','autre','autre','autrefois','autrement','avance','avancer','avant','avant','avec','avec','avenir','aventure','avis','avoir','avouer'),
			
			'b' => array('baisser','banc','bande','barbe','bas','bas','bas','bataille','battre','beau','beau','beau','beaucoup','beaute','beaux','besoin','bete','bien','bien','bientot','billet','blanc','blanc','bleu','blond','boire','bois','bon','bon','bonheur','bord','bouche','bout','branche','bras','briller','briser','bruit','brusquement','brûler','bureau','but'),
			
			'c' => array('ca','cabinet','cacher','calme','calme','calmer','camarade','campagne','capable','car','caractere','caresser','carte','cas','casser','cause','causer','ce','ce','ceci','ceder','cela','celui','cent','centre','cependant','cercle','certain','certain','certainement','certes','cerveau','ces','cesse','cesser','chacun','chaine','chair','chaise','chaleur','chambre','champ','chance','changement','changer','chant','chanter','chaque','charge','charger','chasse','chasser','chat','chaud','chef','chemin','chemise','cher','chercher','cheval','cheveu','chez','chien','chiffre','choisir','choix','chose','chute','ci','ciel','cinq','cinquante','circonstance','clair','claire','classe','clef','coeur','coin','colere','colline','colon','combat','combien','commander','comme','comme','commencement','commencer','comment','comment','commun','compagnie','compagnon','complet','completement','composer','comprendre','compte','compter','conclure','condamner','condition','conduire','confiance','confier','confondre','connaissance','connaitre','conscience','conseil','consentir','considerer','construire','consulter','contenir','content','contenter','continuer','contraire','contre','convenir','conversation','corde','corps','cote','cote','cou','couche','coucher','couler','couleur','coup','couper','cour','courage','courant','courir','cours','course','court','couvrir','coûter','craindre','crainte','creer','creuser','cri','crier','crise','croire','croiser','croix','cruel','cuisine','curieux','curiosite'),
			
			'd' => array('d\'abord','d\'autres','d\'autres','dame','danger','dangereux','dans','danser','davantage','de','de','debout','debut','dechirer','decider','declarer','decouvrir','decrire','defaut','defendre','degager','dehors','dehors','deja','dela','demain','demain','demande','demander','demeurer','demi','dent','depart','depasser','deposer','depuis','depuis','dernier','dernier','derriere','des','des','descendre','desert','desespoir','designer','desir','desirer','desormais','dessiner','dessus','detacher','detail','detourner','detruire','deux','devant','devant','devenir','deviner','devoir','devoir','dieu','different','difficile','digne','dimanche','dire','direction','diriger','discours','discussion','discuter','disparaitre','disposer','distance','distinguer','divers','dix','docteur','doigt','dominer','donc','donner','dont','dormir','dos','double','doucement','douceur','douleur','doute','douter','doux','douze','drame','dresser','droit','droit','droite','droite','drole','du','dur','durant','durer'),
			
			'e' => array('eau','eaux','ecarter','echapper','eclairer','eclat','eclater','ecole','ecouter','ecraser','ecrire','effacer','effet','effort','egal','egalement','eh','element','elever','elle','eloigner','embrasser','emmener','emotion','emparer','empecher','empire','employer','emporter','en','en','en','encore','endormir','endroit','energie','enfance','enfant','enfermer','enfin','enfoncer','engager','enlever','ennemi','enorme','ensemble','ensemble','ensuite','entendre','entier','entourer','entrainer','entre','entree','entrer','entretenir','envelopper','envie','environ','envoyer','epais','epaule','epoque','epreuve','eprouver','erreur','escalier','espace','espece','esperer','espoir','esprit','essayer','essuyer','est','et','etablir','etage','etaler','etat','etc','ete','eteindre','etendre','etendue','eternel','etoile','etonner','etouffer','etrange','etranger','etranger','etre','etre','etroit','etude','etudier','evenement','evidemment','eviter','examiner','executer','exemple','exiger','existence','exister','experience','explication','expliquer','exposer','expression','exprimer','extraordinaire','extreme'),
			
			'f' => array('face','facile','facon','faible','faim','faire','fais','fait','fait','falloir','famille','fatigue','fatiguer','faute','fauteuil','faux','faveur','femme','fenetre','fer','ferme','ferme','fermer','fete','feu','feuille','fidele','fier','figure','figurer','fil','fille','fils','fin','fin','fine','finir','fixe','fixer','flamme','fleur','flot','foi','fois','folie','fonction','fond','fonder','force','forcer','foret','forme','former','fort','fort','fortune','fou','foule','frais','franc','francais','francais','franchir','francois','frapper','frere','froid','froid','front','fruit','fuir','fumee','fumer','fusil'),
			
			'g' => array('gagner','garcon','garde','garder','gauche','gauche','general','general','genou','genre','gens','geste','glace','glisser','gloire','goutte','gouvernement','goût','grace','grace','grain','grand','grand','grandir','grave','gre','gris','gros','groupe','guere','guerre','guider'),
			
			'h' => array('habiller','habitant','habiter','habitude','haine','hasard','haut','haut','haut','haute','hauteur','haïr','herbe','hesiter','heure','heureux','heurter','hier','histoire','hiver','homme','honneur','honte','horizon','hors','hotel','huit','humain','humide'),
			
			'i' => array('ici','idee','ignorer','il','ile','illusion','image','imaginer','immediatement','immense','immobile','importance','important','importer','imposer','impossible','impression','incapable','inconnu','indiquer','inquieter','inquietude','inspirer','installer','instant','instinct','instrument','intelligence','intention','interesser','interet','interieur','interieur','interroger','interrompre','inutile','inventer','inviter'),
			
			'j' => array('jamais','jambe','jardin','jaune','je','jeter','jeu','jeune','jeune','jeunesse','joie','joindre','joli','joue','jouer','jour','journal','journee','juge','juger','juif','jusque','juste','justice'),
			
			'k' => array('k'),
			
			'l' => array('l\'un','l\'une','la','la','large','larme','le','le','lecon','leger','lendemain','lentement','lequel','les','lettre','leur','leur','lever','levre','liberte','libre','lien','lier','lieu','ligne','lire','lisser','lit','livre','livrer','loi','loin','long','long','longtemps','lors','lorsque','loup','lourd','lueur','lui','lumiere','lune','lutte','lutter'),
			
			'm' => array('ma','machine','madame','magnifique','main','maintenant','maintenir','mais','maison','maitre','mal','mal','malade','maladie','malgre','malheur','manche','manger','manier','manquer','marchand','marche','marche','marcher','mari','mari','mariage','marier','marquer','masse','matiere','matin','mauvais','me','medecin','meilleur','meilleur','meler','membre','meme','meme','meme','memoire','menacer','mener','mensonge','mentir','mer','meriter','mesure','metier','mettre','midi','mien','mieux','milieu','militaire','mille','million','mince','mine','ministre','minute','miser','mode','moi','moindre','moins','mois','moitie','moment','mon','monde','monsieur','montagne','monter','montrer','morceau','mort','mort','mot','mourir','mouvement','moyen','moyen','muet','mur','musique'),
			
			'n' => array('naissance','naitre','nation','nature','naturel','naturellement','ne','necessaire','nerveux','neuf','neuf','nez','ni','noir','noir','noire','nom','nombre','nombreux','nommer','non','nord','note','notre','nourrir','nous','nouveau','nouveau','noyer','nu','nuage','nuit','nul'),
			
			'o' => array('obeir','objet','obliger','observer','obtenir','occasion','occuper','odeur','oeil','oeuvre','officier','offrir','oh','oiseau','ombre','on','oncle','or','or','ordre','oreille','oser','ou','oublier','oui','ouvert','ouvrage','ouvrir','où'),
			
			'p' => array('page','pain','paix','palais','papa','papier','paquet','par','paraitre','parce que','parcourir','pareil','parent','parer','parfait','parfaitement','parfois','parler','parmi','parole','part','partager','parti','particulier','partie','partir','partout','parvenir','pas','pas','passage','passe','passe','passer','passion','patron','paupiere','pauvre','pauvre','payer','pays','paysage','paysan','peau','peine','pencher','pendant','pendre','penetrer','pensee','penser','perdre','perdu','pere','permettre','personnage','personne','personne','perte','peser','petit','petit','peu','peuple','peur','phrase','piece','pied','pierre','piquer','pitie','place','placer','plaindre','plaine','plaire','plaisir','plan','planche','plante','plein','plein','pleurer','plier','plonger','pluie','plus','plusieurs','plutot','poche','poesie','poete','poids','point','point','pointe','poitrine','police','politique','politique','pont','port','porte','porter','portier','poser','position','posseder','possible','poste','pour','pourquoi','pourquoi','poursuivre','pourtant','pousser','poussiere','pouvoir','pouvoir','preceder','precieux','precipiter','precis','preferer','premier','premier','prendre','preparer','pres','pres','presence','present','present','presenter','president','presque','presser','pret','pretendre','preter','preuve','prevenir','prevoir','prier','priere','prince','principe','printemps','prison','prix','probablement','probleme','prochain','produire','professeur','profiter','profond','profondement','projet','promener','promettre','prononcer','propos','proposer','propre','proteger','prouver','public','public','puis','puis','puisque','puissance','puissant','pur'),
			
			'q' => array('qualite','quand','quant a','quarante','quart','quartier','quatre','que','que','quel','quelqu\'un','quelque','quelque','question','queue','qui','quinze','quitter','quoi'),
			
			'r' => array('race','raconter','rage','raison','ramasser','ramener','rang','rapide','rapidement','rappeler','rapport','rapporter','rare','rassurer','rayon','realite','recevoir','recherche','reclamer','recommencer','reconnaitre','recueillir','reculer','redevenir','reduire','reel','reflechir','reflexion','refuser','regard','regarder','regle','regretter','regulier','rejeter','rejoindre','relation','relever','religion','remarquer','remercier','remettre','remonter','remplacer','remplir','rencontre','rencontrer','rendre','renoncer','rentrer','renverser','repandre','repas','repeter','repondre','reponse','reposer','repousser','reprendre','representer','reproche','reserver','resistance','resister','resoudre','respect','respecter','respirer','ressembler','reste','rester','resultat','retenir','retirer','retomber','retour','retourner','retrouver','reunir','reussir','reve','reveiller','reveler','revenir','rever','revoir','revolution','riche','rideau','rien','rire','rire','risquer','robe','roche','rocher','roi','role','roman','rompre','rond','rose','rose','rouge','rouge','rouler','route','rue','ruine'),
			
			's' => array('sable','sac','saint','saint','saisir','saison','salle','saluer','salut','sang','sans','sante','satisfaire','sauter','sauvage','sauver','savoir','savoir','scene','science','se','sec','second','seconde','secours','secret','secret','secretaire','seigneur','sein','selon','semaine','semblable','sembler','semer','sens','sentier','sentiment','sentir','separer','sept','serieux','serrer','service','servir','seuil','seul','seulement','si','si','siecle','siege','sien','signe','signer','signifier','silence','silencieux','simple','simplement','situation','six','social','societe','soi','soin','soir','soiree','soit','sol','soldat','soleil','solitude','sombre','somme','sommeil','sommet','son','son','songer','sonner','sorte','sortir','sou','souci','soudain','souffler','souffrance','souffrir','souhaiter','soulever','soumettre','source','sourd','sourire','sourire','sous','soutenir','souvenir','souvenir','souvent','spectacle','subir','succes','sueur','suffire','suite','suivant','suivre','sujet','superieur','supporter','supposer','sur','surprendre','surtout','surveiller','systeme','sûr'),
			
			't' => array('table','tache','tache','taille','taire','tandis que','tant','tantot','tapis','tard','te','tel','tel','tellement','temoin','tempete','temps','tendre','tendre','tenir','tenter','terme','terminer','terrain','terre','terreur','terrible','tes','tete','theatre','tirer','titre','toi','toile','toit','tombe','tomber','ton','ton','tot','toucher','toujours','tour','tourner','tout','tout','tout','tout','toute','trace','tracer','train','trainer','trait','traiter','tranquille','transformer','travail','travailler','travers','traverser','trembler','trente','tres','tresor','triste','trois','troisieme','tromper','trop','trou','troubler','trouver','tu','tuer','type'),
			
			'u' => array('un','un','un','une','unique','usage','user'),
			
			'v' => array('vague','vague','vaincre','valeur','valoir','vaste','veille','veiller','vendre','venir','vent','ventre','veritable','verite','verre','vers','vers','verser','vert','vetement','vetir','victime','vide','vide','vie','vieil','vieillard','vieux','vieux','vif','village','ville','vin','vingt','violence','violent','visage','visible','vision','visite','visiter','vite','vivant','vivre','voici','voie','voila','voile','voir','voisin','voisin','voiture','voix','vol','voler','volonte','votre','vouloir','vous','voyage','voyager','vrai','vraiment','vue'),
			
			'w' => array('w'),
			
			'x' => array('x'),
			
			'y' => array('y','yeux'),
			
			'z' => array('z')
		);
	}
}
